### ISSUE TITLE
Initialize Labs Outline

### ISSUE THREAD

**Issue by dwijaybane** [ELSPL/RoboticsStudyGroup#23]
## New feature description
Create "Labs" folder in Repo
Create README.md for Labs, which will contain outline of Labs

Create Lab0 folder with Pre-requisite .ipynb's
Prerequisite are:

- [ ] Git and Github Tutorial using from ipynb notebook
- [ ] Basic Python Tutorial
- [ ] Pandas Tutorial

Once you start working on an issue mark it "Status: in progress" so others know someone is working on it. If you cannot mark it contact maintainer to resolve it.

**Comment by ranahiren27** [comment]
@dwijaybane I'm Working on this issue

**Comment by dwijaybane** [comment]
Make sure you add compiled form of notebooks rather than just links. The idea is to try working with python and pandas and collect different useful techniques at one place. I am committing current changes. take reference of ml-community in ELSPL.
